#!/bin/bash
export NODE_VIRTUAL_ENV=${1}/extensions/node/_runtime/nodejs
export NODE_PATH=${NODE_VIRTUAL_ENV}/lib/node_modules
export NPM_CONFIG_PREFIX=${NODE_VIRTUAL_ENV};
export PATH=${NODE_VIRTUAL_ENV}/bin:${NODE_PATH}/.bin:$PATH
node --inspect ${1}/extensions/node/main.js ${2} ${3} ${4}
